name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install required system libraries
      run: sudo apt install libxkbcommon-dev
    # selecting a toolchain either by action or manual `rustup` calls should happen
    # before the plugin, as the cache uses the current rustc version as its cache key
    - name: Install Rust
      run: rustup toolchain install stable
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
    - name: Check
      run: cargo check
    - name: Check formatting
      run: cargo fmt --check
    - name: Check lint
      run: cargo clippy --verbose -- -D warnings
    - name: Test
      run: cargo test
